apiVersion: v1
kind: Secret
metadata:
  name: secrets-name
type: Opaque
stringData:
  POSTGRES_DB: main
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
